/**
 * Demo showing the final experiment goals generated by our Shopify signal generation model
 * Run with: npx tsx src/features/signal_generation/final-goals-demo.ts
 */

import 'dotenv/config';
import { createShopifySignalGenerator } from './shopify-signal-generator';
import { PageType } from '@shared/page-types';
import { SignalGenerationInput } from './types';

// Mock analytics repository
class MockAnalyticsRepository {
  async findMany() { return []; }
  async count() { return 0; }
  async create() { return { id: 'mock-1', projectId: 'proj-123', eventType: 'PAGEVIEW' as const, sessionId: 'session-1', viewId: 'view-1', properties: {}, timestamp: Date.now(), createdAt: new Date() }; }
  async createMany() { return []; }
  async getFunnelAnalysis() { return { experimentId: 'exp-123', variants: [], overallStats: { totalSessions: 0, totalExposures: 0, totalConversions: 0, overallConversionRate: 0 }, steps: [], conversionRates: [] }; }
  async getConversionRate() { return 0.15; }
  async getPurchaseStats() { return []; }
  async getExposureStats() { return []; }
  async getExperimentSessions() { return { sessions: [], total: 0 }; }
  async getConversionRates() { return []; }
  async getUserJourney() { return []; }
  async getEventsWithAttribution() { return []; }
  async deleteExperimentEvents() { return 0; }
}

function displayExperimentGoals(experimentName: string, signals: any) {
  console.log(`\n🎯 ${experimentName}`);
  console.log('=' .repeat(60));
  
  console.log('📊 PRIMARY GOAL:');
  console.log(`   Name: ${signals.primary?.name}`);
  console.log(`   Type: ${signals.primary?.type}`);
  console.log(`   Selector: ${signals.primary?.selector || 'None'}`);
  console.log(`   Exists in Control: ${signals.primary?.existsInControl}`);
  console.log(`   Exists in Variant: ${signals.primary?.existsInVariant}`);
  
  if (signals.mechanisms && signals.mechanisms.length > 0) {
    console.log('\n🔧 MECHANISM GOALS:');
    signals.mechanisms.forEach((signal: any, index: number) => {
      console.log(`   ${index + 1}. ${signal.name} (${signal.type})`);
      if (signal.selector) {
        console.log(`      └─ Selector: ${signal.selector}`);
      }
    });
  }
  
  if (signals.guardrails && signals.guardrails.length > 0) {
    console.log('\n🛡️  GUARDRAIL GOALS:');
    signals.guardrails.forEach((signal: any, index: number) => {
      console.log(`   ${index + 1}. ${signal.name} (${signal.type})`);
      if (signal.selector) {
        console.log(`      └─ Selector: ${signal.selector}`);
      }
    });
  }
  
  console.log('\n💭 LLM RATIONALE:');
  console.log(`   ${signals.rationale}`);
  
  console.log('\n📈 MEASUREMENT STRATEGY:');
  console.log('   The system will track:');
  if (signals.primary?.selector?.startsWith('url:')) {
    const targetUrl = signals.primary.selector.replace('url:', '');
    console.log(`   • Page views on ${targetUrl} (Primary Goal)`);
  } else {
    console.log(`   • ${signals.primary?.name} events (Primary Goal)`);
  }
  
  if (signals.mechanisms) {
    signals.mechanisms.forEach((signal: any) => {
      if (signal.selector) {
        console.log(`   • ${signal.name} on ${signal.selector} (Mechanism)`);
      } else {
        console.log(`   • ${signal.name} events (Mechanism)`);
      }
    });
  }
  
  if (signals.guardrails) {
    signals.guardrails.forEach((signal: any) => {
      console.log(`   • ${signal.name} events (Guardrail)`);
    });
  }
}

async function runFinalGoalsDemo() {
  console.log('🚀 Final Experiment Goals Demo');
  console.log('This shows the complete experiment goals generated by our Shopify signal generation model\n');

  const analyticsRepo = new MockAnalyticsRepository();
  const generator = createShopifySignalGenerator(analyticsRepo);

  // Demo 1: Collection Page Clickthrough
  console.log('📱 Demo 1: Collection Page Clickthrough Experiment');
  const collectionInput: SignalGenerationInput = {
    projectId: 'proj-123',
    pageType: PageType.HOME,
    url: 'https://shop.com',
    intent: 'Increase clickthrough rate from homepage to /collections/jeans page by adding a prominent "Shop Jeans" button',
    dom: '<div class="homepage"><div class="hero"><h1>Welcome to Our Store</h1></div></div>',
    variant: {
      changeType: 'addElement',
      selector: '.jeans-cta',
      description: 'Add prominent "Shop Jeans" button linking to /collections/jeans',
      rationale: 'Visible CTAs drive more traffic to specific collections'
    }
  };

  try {
    const collectionSignals = await generator.generateSignals(collectionInput);
    displayExperimentGoals('Collection Page Clickthrough', collectionSignals);
  } catch (error) {
    console.log('❌ Error:', (error as Error).message);
  }

  // Demo 2: Product Page Conversion
  console.log('\n📱 Demo 2: Product Page Conversion Experiment');
  const productInput: SignalGenerationInput = {
    projectId: 'proj-123',
    pageType: PageType.PDP,
    url: 'https://shop.com/products/premium-jeans',
    intent: 'Increase add-to-cart conversion rate by making the button more prominent and adding urgency messaging',
    dom: '<div class="product-page"><h1>Premium Jeans</h1><button class="add-to-cart">Add to Cart</button></div>',
    variant: {
      changeType: 'modifyElement',
      selector: '.add-to-cart',
      description: 'Make button larger, add red color, and add "Limited Time - Only 3 Left!" text',
      rationale: 'Larger, more prominent buttons with urgency messaging drive more conversions'
    }
  };

  try {
    const productSignals = await generator.generateSignals(productInput);
    displayExperimentGoals('Product Page Conversion', productSignals);
  } catch (error) {
    console.log('❌ Error:', (error as Error).message);
  }

  // Demo 3: Checkout Optimization
  console.log('\n📱 Demo 3: Checkout Optimization Experiment');
  const checkoutInput: SignalGenerationInput = {
    projectId: 'proj-123',
    pageType: PageType.CHECKOUT,
    url: 'https://shop.com/checkout',
    intent: 'Reduce checkout abandonment by simplifying the form and adding trust signals',
    dom: '<form class="checkout-form"><input type="email" placeholder="Email" /><button type="submit">Complete Purchase</button></form>',
    variant: {
      changeType: 'modifyElement',
      selector: '.checkout-form',
      description: 'Remove non-essential fields, add security badges, and progress bar',
      rationale: 'Simpler forms with trust signals reduce abandonment'
    }
  };

  try {
    const checkoutSignals = await generator.generateSignals(checkoutInput);
    displayExperimentGoals('Checkout Optimization', checkoutSignals);
  } catch (error) {
    console.log('❌ Error:', (error as Error).message);
  }

  // Demo 4: Newsletter Signup
  console.log('\n📱 Demo 4: Newsletter Signup Experiment');
  const newsletterInput: SignalGenerationInput = {
    projectId: 'proj-123',
    pageType: PageType.HOME,
    url: 'https://shop.com',
    intent: 'Increase newsletter signups with a prominent popup modal offering 10% discount',
    dom: '<div class="homepage"><div class="hero"><h1>Welcome to Our Store</h1></div></div>',
    variant: {
      changeType: 'addElement',
      selector: '.newsletter-popup',
      description: 'Add newsletter signup popup modal with 10% discount offer',
      rationale: 'Popups with incentives capture attention and drive signups'
    }
  };

  try {
    const newsletterSignals = await generator.generateSignals(newsletterInput);
    displayExperimentGoals('Newsletter Signup', newsletterSignals);
  } catch (error) {
    console.log('❌ Error:', (error as Error).message);
  }

  console.log('\n🎯 SUMMARY:');
  console.log('Our model generates intelligent experiment goals that:');
  console.log('1. 🎯 Target the right metrics based on experiment intent');
  console.log('2. 🔧 Include mechanism goals to understand WHY changes work');
  console.log('3. 🛡️  Add guardrail goals to prevent false wins');
  console.log('4. 📊 Use precise URL targeting for clickthrough experiments');
  console.log('5. 💡 Provide clear rationale for every goal choice');
  console.log('6. 🧠 Adapt to any experiment type automatically');
}

// Run the demo
if (require.main === module) {
  runFinalGoalsDemo().catch(console.error);
}

export { runFinalGoalsDemo };
